# Generated by Django 4.2.4 on 2023-09-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_cart_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=True)),
                ('product_name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Qty', models.PositiveIntegerField(default=1)),
                ('price', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('PACKED', 'PACKED'), ('ON THE WAY', 'ON THE WAY'), ('DILIVERD', 'DILIVERD'), ('CANCEL', 'CANCEL')], default='padding', max_length=50)),
            ],
        ),
    ]
