# Generated by Django 4.2.4 on 2023-09-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.BigIntegerField(default=True),
        ),
    ]
